#!/usr/bin/env bash
# THIS FILE IS GENERATED BY tools/setup_python.sh
export PYTHONUSERBASE="/dccstor/cssblr/ashish/dvrl/espnet/tools/python_user_base"
export PATH="/dccstor/cssblr/ashish/dvrl/espnet/tools/python_user_base/bin":${PATH}
export PATH=/dccstor/cssblr/ashish/dvrl/espnet/tools/venv/bin:${PATH}
